In [1]:
import requests
import json
import numpy as np
import pandas as pd
import time
import seaborn as sns

In [2]:
url = 'https://auto.ru/-/ajax/desktop/listing/'

In [3]:
columns = {
    'id': 'id',
    'bodyType': ['vehicle_info', 'configuration', 'human_name'],
    'brand': ['vehicle_info', 'mark_info', 'name'],
           'color': 'color_hex', 
           'complectation_dict': ['vehicle_info', 'complectation'],
           'description': 'description',
           'engineDisplacement': ['vehicle_info', 'tech_param', 'human_name'],
           'enginePower': ['vehicle_info', 'tech_param', 'power'], 
           'equipment_dict': ['vehicle_info', 'equipment'], 
           'fuelType': ['vehicle_info', 'tech_param', 'engine_type'], 
           'mileage': ['state', 'mileage'], 
           'modelDate': ['documents', 'year'], 
           'model_info': ['vehicle_info', 'model_info'],
           'model_name': ['vehicle_info', 'model_info', 'name'],
           'name': ['vehicle_info', 'tech_param', 'human_name'], 
           'numberOfDoors': ['vehicle_info','configuration', 'doors_count'], 
           'priceCurrency': ['price_info', 'currency'], 
           'productionDate': ['documents', 'year'], 
           'sell_id': 'saleId', 
           'super_gen': ['vehicle_info', 'tech_param'], 
           'vehicleConfiguration': ['vehicle_info', 'configuration'], 
           'vehicleTransmission': ['vehicle_info', 'tech_param', 'transmission'], 
           'vendor': ['vehicle_info', 'vendor'], 
           'ownership': ['documents', 'owners_number'], 
           'owner': ['documents', 'owners_number'], 
           'PTS': ['documents', 'pts'], 
           'gear': ['vehicle_info' ,'tech_param', 'gear_type'], 
           'helm': ['vehicle_info', 'steering_wheel'], 
           'condition': ['state', 'state_not_beaten'], 
           'customs': ['documents', 'custom_cleared'], 
           'price': ['price_info', 'price'],
        'warranty': ['documents', 'warranty'],
    'used_new': 'section',
    'body_type': ['vehicle_info', 'configuration', 'body_type'],
    'price_segment': ['vehicle_info', 'super_gen', 'price_segment'],
    'purpose_group': ['vehicle_info', 'super_gen', 'purpose_group'],
    'url_data1': ['vehicle_info', 'mark_info', 'code'],
    'url_data2': ['vehicle_info', 'model_info', 'code'],
    'url_data3': 'saleId'
}

In [4]:
df_data = {
    'id': [],
    'bodyType': [],
    'brand': [],
           'color': [], 
           'complectation_dict': [],
           'description': [],
           'engineDisplacement': [],
           'enginePower': [], 
           'equipment_dict': [], 
           'fuelType': [], 
           'mileage': [], 
           'modelDate': [], 
           'model_info': [],
           'model_name': [],
           'name': [], 
           'numberOfDoors': [], 
           'priceCurrency': [], 
           'productionDate': [], 
           'sell_id': [], 
           'super_gen': [], 
           'vehicleConfiguration': [], 
           'vehicleTransmission': [], 
           'vendor': [], 
           'ownership': [], 
           'owner': [], 
           'PTS': [], 
           'gear': [], 
           'helm': [], 
           'condition': [], 
           'customs': [], 
           'price': [],
        'warranty': [],
    'used_new': [],
    'body_type': [],
    'price_segment': [],
    'purpose_group': [],
    'url_data1': [],
    'url_data2': [],
    'url_data3': []
}

In [5]:
for page in range(100):
    headers = """
Host: auto.ru
Connection: keep-alive
Content-Length: 77
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
x-client-date: 1637580771998
x-csrf-token: abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8
x-page-request-id: ab339b19fbb0c89901545dd07ed76b3d
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.0.1996 Yowser/2.5 Safari/537.36
x-client-app-version: 4dee3c737e6
x-requested-with: fetch
content-type: application/json
sec-ch-ua-platform: "Windows"
Accept: */*
Origin: https://auto.ru
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: same-origin
Sec-Fetch-Dest: empty
Referer: https://auto.ru/moskva/cars/all/do-100000/?page={page}
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en;q=0.9
Cookie: _csrf_token=abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8; autoru_sid=a%3Ag6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c%7C1637267219701.604800.ufCH_RshHQQ3qjUIzvjIMg.ASX4-Gwrc5-IL5uFQPlhAdWXBcBGoerYB9UAB9U1T04; autoruuid=g6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c; autoru_gdpr=1; suid=26d13bb93b16678b5fb16cabd651e9cd.2005fef10722bda74610a34f6b243591; _yasc=0yftn08FA35m9RWt3Ja2XTpTcOn/CzUYqUgHlU+o/eW2Qg==; yuidlt=1; yandexuid=4128931181617045238; my=YwA%3D; credit_filter_promo_popup_closed=true; index-selector-tab=marks; credit_modal_autoshow_closed=true; gdpr=0; _ym_uid=163726723137333750; _ym_d=1637267329; deal_million_popup_page_seen=-1; gids=213; from=direct; listing_view_session={}; new-controls-notify-hidden=true; mmm-search-accordion-is-open-cars=%5B1%5D; listing_view=%7B%22output_type%22%3Anull%2C%22version%22%3A1%7D; _ym_isad=2; autoru-visits-count=4; safe_deal_promo=0; gradius=0; cycada=RM4hswvgL2u8Yk3TPvPe+I/KaRK1Yn4Vm40t17Pp6FQ=; from_lifetime=1637580739352
    """.strip().split("\n")
    dict_header = {}
    for header in headers:
        key, value = header.split(": ")
        dict_header[key] = value
    params = {"category":"cars",
              "section":"all",
              "price_to":100000,
              "page":page,
              "geo_id":[213]}
    response = requests.post(url, json=params, headers = dict_header)
    data = response.json()
    if 'offers' in data:
        for offer in range(len(data['offers'])):
            for column in columns.keys():
                if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                    df_data[column].append(data['offers'][offer][columns[column]])
                elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                else:
                    df_data[column].append(np.nan)
    else:
        time.sleep(10)
        try:
            response = requests.post(url, json=params, headers = dict_header)
        except:
            continue
        if response.status_code == 200:
            data = response.json()
        else:
            continue
        for offer in range(len(data['offers'])):
            for column in columns.keys():
                if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                    df_data[column].append(data['offers'][offer][columns[column]])
                elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                else:
                    df_data[column].append(np.nan)

In [6]:
for price in range(100000, 10100000, 100000):
    for page in range(100):
        headers = """
Host: auto.ru
Connection: keep-alive
Content-Length: 77
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
x-client-date: 1637580771998
x-csrf-token: abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8
x-page-request-id: ab339b19fbb0c89901545dd07ed76b3d
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.0.1996 Yowser/2.5 Safari/537.36
x-client-app-version: 4dee3c737e6
x-requested-with: fetch
content-type: application/json
sec-ch-ua-platform: "Windows"
Accept: */*
Origin: https://auto.ru
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: same-origin
Sec-Fetch-Dest: empty
Referer: https://auto.ru/moskva/cars/all/?price_from={price}&page={page}&price_to={price+100000}
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en;q=0.9
Cookie: _csrf_token=abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8; autoru_sid=a%3Ag6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c%7C1637267219701.604800.ufCH_RshHQQ3qjUIzvjIMg.ASX4-Gwrc5-IL5uFQPlhAdWXBcBGoerYB9UAB9U1T04; autoruuid=g6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c; autoru_gdpr=1; suid=26d13bb93b16678b5fb16cabd651e9cd.2005fef10722bda74610a34f6b243591; _yasc=0yftn08FA35m9RWt3Ja2XTpTcOn/CzUYqUgHlU+o/eW2Qg==; yuidlt=1; yandexuid=4128931181617045238; my=YwA%3D; credit_filter_promo_popup_closed=true; index-selector-tab=marks; credit_modal_autoshow_closed=true; gdpr=0; _ym_uid=163726723137333750; _ym_d=1637267329; deal_million_popup_page_seen=-1; gids=213; from=direct; listing_view_session={}; new-controls-notify-hidden=true; mmm-search-accordion-is-open-cars=%5B1%5D; listing_view=%7B%22output_type%22%3Anull%2C%22version%22%3A1%7D; _ym_isad=2; autoru-visits-count=4; safe_deal_promo=0; gradius=0; cycada=RM4hswvgL2u8Yk3TPvPe+I/KaRK1Yn4Vm40t17Pp6FQ=; from_lifetime=1637580739352
        """.strip().split("\n")
        dict_header = {}
        for header in headers:
            key, value = header.split(": ")
            dict_header[key] = value
        params = {"category":"cars",
                  "section":"all",
                  "price_from":price,
                  "page":page,
                  "price_to":price+100000,
                  "geo_id":[213]}
        try:
            response = requests.post(url, json=params, headers = dict_header)
        except:
            continue
        if response.status_code == 200:
            data = response.json()
        else:
            time.sleep(5)
            try:
                response = requests.post(url, json=params, headers = dict_header)
            except:
                continue
            if response.status_code == 200:
                data = response.json()
            else:
                continue
        if 'offers' in data:
            for offer in range(len(data['offers'])):
                for column in columns.keys():
                    if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                        df_data[column].append(data['offers'][offer][columns[column]])
                    elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                    elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                    else:
                        df_data[column].append(np.nan)
        else:
            time.sleep(10)
            try:
                response = requests.post(url, json=params, headers = dict_header)
            except:
                continue
            if response.status_code == 200:
                data = response.json()
            else:
                continue
            for offer in range(len(data['offers'])):
                for column in columns.keys():
                    if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                        df_data[column].append(data['offers'][offer][columns[column]])
                    elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                    elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                    else:
                        df_data[column].append(np.nan)

In [7]:
for price in range(10000000, 25000000, 5000000):
    for page in range(100):
        headers = """
Host: auto.ru
Connection: keep-alive
Content-Length: 77
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
x-client-date: 1637580771998
x-csrf-token: abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8
x-page-request-id: ab339b19fbb0c89901545dd07ed76b3d
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.0.1996 Yowser/2.5 Safari/537.36
x-client-app-version: 4dee3c737e6
x-requested-with: fetch
content-type: application/json
sec-ch-ua-platform: "Windows"
Accept: */*
Origin: https://auto.ru
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: same-origin
Sec-Fetch-Dest: empty
Referer: https://auto.ru/moskva/cars/all/?price_from={price}&page={page}&price_to={price+5000000}
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en;q=0.9
Cookie: _csrf_token=abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8; autoru_sid=a%3Ag6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c%7C1637267219701.604800.ufCH_RshHQQ3qjUIzvjIMg.ASX4-Gwrc5-IL5uFQPlhAdWXBcBGoerYB9UAB9U1T04; autoruuid=g6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c; autoru_gdpr=1; suid=26d13bb93b16678b5fb16cabd651e9cd.2005fef10722bda74610a34f6b243591; _yasc=0yftn08FA35m9RWt3Ja2XTpTcOn/CzUYqUgHlU+o/eW2Qg==; yuidlt=1; yandexuid=4128931181617045238; my=YwA%3D; credit_filter_promo_popup_closed=true; index-selector-tab=marks; credit_modal_autoshow_closed=true; gdpr=0; _ym_uid=163726723137333750; _ym_d=1637267329; deal_million_popup_page_seen=-1; gids=213; from=direct; listing_view_session={}; new-controls-notify-hidden=true; mmm-search-accordion-is-open-cars=%5B1%5D; listing_view=%7B%22output_type%22%3Anull%2C%22version%22%3A1%7D; _ym_isad=2; autoru-visits-count=4; safe_deal_promo=0; gradius=0; cycada=RM4hswvgL2u8Yk3TPvPe+I/KaRK1Yn4Vm40t17Pp6FQ=; from_lifetime=1637580739352
        """.strip().split("\n")
        dict_header = {}
        for header in headers:
            key, value = header.split(": ")
            dict_header[key] = value
        params = {"category":"cars",
                  "section":"all",
                  "price_from":price,
                  "page":page,
                  "price_to":price+5000000,
                  "geo_id":[213]}
        try:
            response = requests.post(url, json=params, headers = dict_header)
        except:
            continue
        if response.status_code == 200:
            data = response.json()
        else:
            time.sleep(5)
            try:
                response = requests.post(url, json=params, headers = dict_header)
            except:
                continue
            if response.status_code == 200:
                data = response.json()
            else:
                continue
        if 'offers' in data:
            for offer in range(len(data['offers'])):
                for column in columns.keys():
                    if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                        df_data[column].append(data['offers'][offer][columns[column]])
                    elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                    elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                    else:
                        df_data[column].append(np.nan)
        else:
            time.sleep(10)
            try:
                response = requests.post(url, json=params, headers = dict_header)
            except:
                continue
            if response.status_code == 200:
                data = response.json()
            else:
                continue
            for offer in range(len(data['offers'])):
                for column in columns.keys():
                    if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                        df_data[column].append(data['offers'][offer][columns[column]])
                    elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                    elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                        df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                    else:
                        df_data[column].append(np.nan)

In [8]:
for page in range(100):
    headers = """
Host: auto.ru
Connection: keep-alive
Content-Length: 77
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
x-client-date: 1637580771998
x-csrf-token: abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8
x-page-request-id: ab339b19fbb0c89901545dd07ed76b3d
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.0.1996 Yowser/2.5 Safari/537.36
x-client-app-version: 4dee3c737e6
x-requested-with: fetch
content-type: application/json
sec-ch-ua-platform: "Windows"
Accept: */*
Origin: https://auto.ru
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: same-origin
Sec-Fetch-Dest: empty
Referer: https://auto.ru/moskva/cars/all/?price_from=15000000&page={page}
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en;q=0.9
Cookie: _csrf_token=abc86d2c8bf75efa7f210aa4e928a13348a94f403e2125f8; autoru_sid=a%3Ag6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c%7C1637267219701.604800.ufCH_RshHQQ3qjUIzvjIMg.ASX4-Gwrc5-IL5uFQPlhAdWXBcBGoerYB9UAB9U1T04; autoruuid=g6196b71329ln81jrkfjqemnjdk6uf50.6dac3215c3de1f15b6785d4e9893436c; autoru_gdpr=1; suid=26d13bb93b16678b5fb16cabd651e9cd.2005fef10722bda74610a34f6b243591; _yasc=0yftn08FA35m9RWt3Ja2XTpTcOn/CzUYqUgHlU+o/eW2Qg==; yuidlt=1; yandexuid=4128931181617045238; my=YwA%3D; credit_filter_promo_popup_closed=true; index-selector-tab=marks; credit_modal_autoshow_closed=true; gdpr=0; _ym_uid=163726723137333750; _ym_d=1637267329; deal_million_popup_page_seen=-1; gids=213; from=direct; listing_view_session={}; new-controls-notify-hidden=true; mmm-search-accordion-is-open-cars=%5B1%5D; listing_view=%7B%22output_type%22%3Anull%2C%22version%22%3A1%7D; _ym_isad=2; autoru-visits-count=4; safe_deal_promo=0; gradius=0; cycada=RM4hswvgL2u8Yk3TPvPe+I/KaRK1Yn4Vm40t17Pp6FQ=; from_lifetime=1637580739352
        """.strip().split("\n")
    dict_header = {}
    for header in headers:
        key, value = header.split(": ")
        dict_header[key] = value
    params = {"category":"cars",
                "section":"all",
                "price_from":15000000,
                "page":page,
                "geo_id":[213]}
    try:
        response = requests.post(url, json=params, headers = dict_header)
    except:
        continue
    if response.status_code == 200:
        data = response.json()
    else:
        time.sleep(5)
        try:
            response = requests.post(url, json=params, headers = dict_header)
        except:
            continue
        if response.status_code == 200:
            data = response.json()
        else:
            continue
    if 'offers' in data:
        for offer in range(len(data['offers'])):
            for column in columns.keys():
                if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                    df_data[column].append(data['offers'][offer][columns[column]])
                elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                else:
                    df_data[column].append(np.nan)
    else:
        time.sleep(10)
        try:
            response = requests.post(url, json=params, headers = dict_header)
        except:
            continue
        if response.status_code == 200:
            data = response.json()
        else:
            continue
        for offer in range(len(data['offers'])):
            for column in columns.keys():
                if type(columns[column]) == type(str('str')) and columns[column] in data['offers'][offer].keys():
                    df_data[column].append(data['offers'][offer][columns[column]])
                elif len(columns[column]) == 2 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]])
                elif len(columns[column]) == 3 and columns[column][0] in data['offers'][offer] and columns[column][1] in data['offers'][offer][columns[column][0]] and columns[column][2] in data['offers'][offer][columns[column][0]][columns[column][1]]:
                    df_data[column].append(data['offers'][offer][columns[column][0]][columns[column][1]][columns[column][2]])
                else:
                    df_data[column].append(np.nan)

In [9]:
df = pd.DataFrame(df_data)
df = df.drop_duplicates(subset=['url_data3']).reset_index()
df.to_excel('auto_ru_data_11_22_2022.xlsx')

In [10]:
df = df.dropna(subset=['price'])
df = df.dropna(subset=['PTS'])
df['ownership'] = df['ownership'].fillna(0)
df['owner'] = df['owner'].fillna(0)
df['warranty'] = df['warranty'].fillna(0)
df['warranty'] = df['warranty'].replace(bool(1), 1)
urls = []
for index, row in df.iterrows():
    urls.append('https://auto.ru/cars/'+row['used_new']+'/sale/'+row['url_data1']+'/'+row['url_data2']+'/'+row['url_data3'])
df['car_url'] = urls
df = df.drop(['url_data1', 'url_data2', 'url_data3', 'index'], axis=1)

In [11]:
df[df.describe().columns]

,enginePower,mileage,modelDate,numberOfDoors,productionDate,ownership,owner,price,warranty
0,64,107000,1984,4,1984,2.0,2.0,50000.0,0
1,75,70000,2004,4,2004,3.0,3.0,60000.0,0
2,64,82000,1994,4,1994,4.0,4.0,80000.0,0
3,72,34000,2007,5,2007,2.0,2.0,80000.0,0
4,122,178000,1997,5,1997,4.0,4.0,110000.0,0
...,...,...,...,...,...,...,...,...,...
73419,480,0,2021,5,2021,0.0,0.0,21200000.0,0
73420,558,0,2021,5,2021,0.0,0.0,34180000.0,0
73421,558,0,2021,5,2021,0.0,0.0,32690000.0,0
73422,585,0,2021,5,2021,0.0,0.0,29660000.0,1
73423,585,0,2021,5,2021,0.0,0.0,29590000.0,1